[build]
  # Este es el comando que Netlify usar치 para compilar tu app.
  # Se cambi칩 a 'netlify' para que use la configuraci칩n con baseHref="/"
  command = "ng build --configuration netlify"

  # Este es el directorio donde se encuentran los archivos compilados.
  publish = "dist/geodais/browser"

# Regla de redirecci칩n para que funcionen las rutas de la SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
